[package]
name = "tmq"
version = "0.1.0"
authors = ["cetra3 <cetra3@hotmail.com>"]
license = "MIT/Apache-2.0"
description = "ZeroMQ bindings for Tokio"
repository = "https://github.com/cetra3/tmq"
readme = "README.md"
edition = "2018"

[dependencies]
bytes = "0.4"
futures-preview = "0.3.0-alpha.17"
mio = "0.6"
tokio = "0.2.0-alpha.1"
tokio-io = "0.2.0-alpha.1"
tokio-reactor = "0.2.0-alpha.1"
zmq = "0.9.0"
log = "0.4"
quick-error = "1.2"

[dev-dependencies]
pretty_env_logger = "0.2"
rand = "0.7"
criterion = "0.2"

[[bench]]
name = "poll"
harness = false
